image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine

before_script:
  - docker login -u ${REGISTRY_LOGIN} -p ${REGISTRY_PASSWORD} ${REGISTRY_URL}

stages:
  - build
  - test
  - deploy


build_dotnet:
  stage: build
  script:
    - cd src
    - dotnet restore
    - dotnet build


build_js:
  stage: build
  script:
    - cd src/VueClient
    - npm install
    - npm run build


test:
  stage: test
  script:
    - cd src
    - dotnet test
  dependencies:
    - build


deploy_staging:
  stage: deploy
  script:
    - ./deploy.sh
  environment:
    name: staging
    url: http://vcm-12801.vm.duke.edu/
  when: manual