before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - cd src
    - dotnet restore
    - dotnet build
    - cd VueClient
    - npm install
    - npm run build


test:
  stage: test
  script:
    - cd src
    - dotnet test
  dependencies:
    - build
    - build


deploy_staging:
  stage: deploy
  script:
    - chmod +x ./deploy.sh
    - docker info
    - docker build -t $CI_PROJECT_PATH -f ./src/Dockerfile .
    - docker tag $CI_PROJECT_PATH $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE
    - ssh vcm@vcm-12801.vm.duke.edu docker run -d -p 80:80 $CI_REGISTRY_IMAGE
  environment:
    name: staging
    url: http://vcm-12801.vm.duke.edu/