stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - cd src
    - dotnet restore
    - dotnet build


test:
  stage: test
  script:
    - cd src
    - dotnet test
  dependencies:
    - build


deploy_staging:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_PROJECT_PATH -f ./src/Dockerfile .
    - docker tag $CI_PROJECT_PATH $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE
    - ssh -t vcm@vcm-12801.vm.duke.edu sudo docker rm $(ssh vcm@vcm-12801.vm.duke.edu sudo docker stop $(ssh vcm@vcm-12801.vm.duke.edu sudo docker ps -a -q --filter ancestor="$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" --format="{{.ID}}"))
    - ssh -t vcm@vcm-12801.vm.duke.edu sudo docker run -d -p 80:80 $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  environment:
    name: staging
    url: http://vcm-12801.vm.duke.edu/