image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - cd src
    - dotnet restore
    - dotnet build


test:
  stage: test
  script:
    - cd src
    - dotnet test


deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://replaceme.example.com
  only:
    - feature/deployments