before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - cd src
    - dotnet restore
    - dotnet build
    - cd VueClient
    - npm install
    - npm run build


test:
  stage: test
  script:
    - cd src
    - dotnet test
  dependencies:
    - build
    - build


deploy_staging:
  stage: deploy
  script:
    - ./deploy.sh
  environment:
    name: staging
    url: http://vcm-12801.vm.duke.edu/
  when: manual