#!/bin/bash

echo 'Retention type ->' $1
echo 'Retention count ->' $2

sudo docker exec Web.Api.Infrastructure.SqlServer bash -c "cd /var/opt/mssql/backup/$1 && ls -1trb /var/opt/mssql/backup/$1 | tail -n +$2 | xargs rm -- 2> /dev/null"

