#!/bin/bash

echo 'Retention type ->' $1

sudo docker exec Web.Api.Infrastructure.SqlServer bash -c "cd /var/opt/mssql/backup/daily && ls -1trb /var/opt/mssql/backup/daily | tail -n +8 | xargs rm -- 2> /dev/null"

