version: '3.4'

services:
  web.api:
    image: ${CI_REGISTRY-}ece458/app:latest
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - "ConnectionStrings__ApplicationDbConnection=Server=db;Database=webapi;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "Web.Api.Infrastructure.SqlServer"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "${DB_PASSWORD:-Password_123}"
      ACCEPT_EULA: "Y"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata: